import { transformWorkoutSet } from "@/bff/transformers";

// ====================== MOCK DATA ======================
const WORKOUT_SETS = [
    {
        id: "uuid-set-1",
        workout_exercise_id: "uuid-wo-ex-1",
        set_number: 1,
        reps: 8,
        weight: 40,
        duration_seconds: null,
        rpe: 6,
    },
    {
        id: "uuid-set-2",
        workout_exercise_id: "uuid-wo-ex-2",
        set_number: 2,
        reps: 9,
        weight: 50,
        duration_seconds: null,
        rpe: 7,
    },
    {
        id: "uuid-set-3",
        workout_exercise_id: "uuid-wo-ex-3",
        set_number: 3,
        reps: 10,
        weight: 60,
        duration_seconds: null,
        rpe: 8,
    },
    {
        id: "uuid-set-4",
        workout_exercise_id: "uuid-wo-ex-4",
        set_number: 4,
        reps: 11,
        weight: 70,
        duration_seconds: null,
        rpe: 6,
    },
    {
        id: "uuid-set-5",
        workout_exercise_id: "uuid-wo-ex-5",
        set_number: 5,
        reps: 12,
        weight: 80,
        duration_seconds: null,
        rpe: 7,
    },
    {
        id: "uuid-set-6",
        workout_exercise_id: "uuid-wo-ex-6",
        set_number: 1,
        reps: 13,
        weight: 90,
        duration_seconds: null,
        rpe: 8,
    },
    {
        id: "uuid-set-7",
        workout_exercise_id: "uuid-wo-ex-7",
        set_number: 2,
        reps: 8,
        weight: 100,
        duration_seconds: null,
        rpe: 6,
    },
    {
        id: "uuid-set-8",
        workout_exercise_id: "uuid-wo-ex-8",
        set_number: 3,
        reps: 9,
        weight: 40,
        duration_seconds: null,
        rpe: 7,
    },
    {
        id: "uuid-set-9",
        workout_exercise_id: "uuid-wo-ex-9",
        set_number: 4,
        reps: 10,
        weight: 50,
        duration_seconds: null,
        rpe: 8,
    },
    {
        id: "uuid-set-10",
        workout_exercise_id: "uuid-wo-ex-10",
        set_number: 5,
        reps: 11,
        weight: 60,
        duration_seconds: null,
        rpe: 6,
    },
    {
        id: "uuid-set-11",
        workout_exercise_id: "uuid-wo-ex-11",
        set_number: 1,
        reps: 12,
        weight: 70,
        duration_seconds: null,
        rpe: 7,
    },
    {
        id: "uuid-set-12",
        workout_exercise_id: "uuid-wo-ex-12",
        set_number: 2,
        reps: 13,
        weight: 80,
        duration_seconds: null,
        rpe: 8,
    },
    {
        id: "uuid-set-13",
        workout_exercise_id: "uuid-wo-ex-13",
        set_number: 3,
        reps: 8,
        weight: 90,
        duration_seconds: null,
        rpe: 6,
    },
    {
        id: "uuid-set-14",
        workout_exercise_id: "uuid-wo-ex-14",
        set_number: 4,
        reps: 9,
        weight: 100,
        duration_seconds: null,
        rpe: 7,
    },
    {
        id: "uuid-set-15",
        workout_exercise_id: "uuid-wo-ex-15",
        set_number: 5,
        reps: 10,
        weight: 40,
        duration_seconds: null,
        rpe: 8,
    },
    {
        id: "uuid-set-16",
        workout_exercise_id: "uuid-wo-ex-16",
        set_number: 1,
        reps: 11,
        weight: 50,
        duration_seconds: null,
        rpe: 6,
    },
    {
        id: "uuid-set-17",
        workout_exercise_id: "uuid-wo-ex-17",
        set_number: 2,
        reps: 12,
        weight: 60,
        duration_seconds: null,
        rpe: 7,
    },
    {
        id: "uuid-set-18",
        workout_exercise_id: "uuid-wo-ex-18",
        set_number: 3,
        reps: 13,
        weight: 70,
        duration_seconds: null,
        rpe: 8,
    },
    {
        id: "uuid-set-19",
        workout_exercise_id: "uuid-wo-ex-19",
        set_number: 4,
        reps: 8,
        weight: 80,
        duration_seconds: null,
        rpe: 6,
    },
    {
        id: "uuid-set-20",
        workout_exercise_id: "uuid-wo-ex-20",
        set_number: 5,
        reps: 9,
        weight: 90,
        duration_seconds: null,
        rpe: 7,
    },
    {
        id: "uuid-set-21",
        workout_exercise_id: "uuid-wo-ex-1",
        set_number: 1,
        reps: 10,
        weight: 100,
        duration_seconds: null,
        rpe: 8,
    },
    {
        id: "uuid-set-22",
        workout_exercise_id: "uuid-wo-ex-2",
        set_number: 2,
        reps: 11,
        weight: 40,
        duration_seconds: null,
        rpe: 6,
    },
    {
        id: "uuid-set-23",
        workout_exercise_id: "uuid-wo-ex-3",
        set_number: 3,
        reps: 12,
        weight: 50,
        duration_seconds: null,
        rpe: 7,
    },
    {
        id: "uuid-set-24",
        workout_exercise_id: "uuid-wo-ex-4",
        set_number: 4,
        reps: 13,
        weight: 60,
        duration_seconds: null,
        rpe: 8,
    },
    {
        id: "uuid-set-25",
        workout_exercise_id: "uuid-wo-ex-5",
        set_number: 5,
        reps: 8,
        weight: 70,
        duration_seconds: null,
        rpe: 6,
    },
    {
        id: "uuid-set-26",
        workout_exercise_id: "uuid-wo-ex-6",
        set_number: 1,
        reps: 9,
        weight: 80,
        duration_seconds: null,
        rpe: 7,
    },
    {
        id: "uuid-set-27",
        workout_exercise_id: "uuid-wo-ex-7",
        set_number: 2,
        reps: 10,
        weight: 90,
        duration_seconds: null,
        rpe: 8,
    },
    {
        id: "uuid-set-28",
        workout_exercise_id: "uuid-wo-ex-8",
        set_number: 3,
        reps: 11,
        weight: 100,
        duration_seconds: null,
        rpe: 6,
    },
    {
        id: "uuid-set-29",
        workout_exercise_id: "uuid-wo-ex-9",
        set_number: 4,
        reps: 12,
        weight: 40,
        duration_seconds: null,
        rpe: 7,
    },
    {
        id: "uuid-set-30",
        workout_exercise_id: "uuid-wo-ex-10",
        set_number: 5,
        reps: 13,
        weight: 50,
        duration_seconds: null,
        rpe: 8,
    },
];

export const getWorkoutSets = async () => {
    try {
        const workoutSets = WORKOUT_SETS.map(transformWorkoutSet);

        return { workoutSets: workoutSets, message: null };
    } catch (err) {
        return {
            workoutSets: null,
            message:
                "Ошибка при получении сетов из тренировки. Попробуйте позже.",
        };
    }
};
